tap "nodenv/nodenv"

brew "mas"

brew "git"
brew "cmake"
brew "earthly"
brew "fzf"
brew "gh"
brew "go"
brew "gpg"
brew "pinentry-mac"
brew "jrnl"
brew "mysql"
brew "node"
brew "nodenv"
brew "nodenv/nodenv/nodenv-default-packages"
brew "postgresql"
brew "prettier"
brew "python"
brew "rbenv"
brew "redis"
brew "ruby-build"
brew "the_silver_searcher"
brew "spark"
brew "reattach-to-user-namespace" # To support tmux
brew "hashicorp/tap/terraform"
brew "tldr"
brew "tmux"
brew "vim"

cask_args appdir: "/Applications"
cask "bunch"
cask "claude"
cask "claude-code"
cask "chatgpt"
cask "codex-app"
cask "choosy"
cask "coderunner"
cask "docker-desktop"
cask "fantastical"
cask "firefox@developer-edition"
cask "gpg-suite"
cask "kaleidoscope"
cask "mailmate"
cask "marked-app"
cask "markedit"
cask "monodraw"
cask "notion"
cask "rapidapi"
cask "quitter"
cask "rocket"
cask "slack"
cask "tableplus"
cask "tower"
cask "transmit"
cask "typora"
cask "zoom"

mas "1Password for Safari", id: 1569813296
mas "Base", id: 402383384
mas "PrettyJSON for Xcode", id: 1396408074
mas "Xcode", id: 497799835

# Fonts
cask "font-source-code-pro"
cask "font-source-sans-3"
cask "font-fira-code-nerd-font"
cask "font-fira-mono"
cask "font-fira-mono-nerd-font"
cask "font-fira-sans"
