""
"" Janus setup
""

" Define paths
"let g:janus_path = escape(fnamemodify(resolve(expand("<sfile>:p" . "janus" . "janus")), ":h"), ' ')
"let g:janus_vim_path = escape(fnamemodify(resolve(expand("<sfile>:p" . "janus" . "janus" . "vim")), ":h"), ' ')"

let g:home_path = expand("~")
let g:vim_path = g:home_path . "/.dotfiles/vim"
let g:janus_path = g:vim_path . "/janus/janus"
let g:janus_vim_path = g:janus_path . "/vim"

let g:janus_custom_path = g:vim_path . "customization"

if filereadable(g:janus_vim_path . '/core/before/plugin/janus.vim')
	" Source janus's core
	exe 'source ' . g:janus_vim_path . '/core/before/plugin/janus.vim'

	" You should note that groups will be processed by Pathogen in reverse
	" order they were added.
	call janus#add_group("tools")
	call janus#add_group("langs")
	call janus#add_group("colors")

	""
	"" Customisations
	""

	if filereadable(expand("~/.vimrc.before"))
	  source ~/.vimrc.before
	endif


	" Disable plugins prior to loading pathogen
	exe 'source ' . g:janus_vim_path . '/core/plugins.vim'

	""
	"" Pathogen setup
	""

	" Load all groups, custom dir, and janus core
	call janus#load_pathogen()

	" .vimrc.after is loaded after the plugins have loaded
endif