export DOTFILES="$HOME/Projects/dotfiles"
export EDITOR='vim'
export GIT_EDITOR='vim'
export BUNDLER_EDITOR='vim'
export HOMEBREW_CASK_OPTS="--appdir=/Applications"
export NODE_PATH="/usr/local/lib/node"

export GOPATH=~/go
export GO15VENDOREXPERIMENT=1
export PATH=$PATH:~/go/bin

export PATH=/opt/boxen/homebrew/bin:$HOME/bin:$HOME/bin/Multimarkdown/bin:$HOME/bin/abbot/bin:/usr/bin:opt/local/bin:/opt/local/sbin:/bin:/sbin:$PATH

export GIT_CONFIG_NOSYSTEM=1
if [[ ! -L $HOME/.gitconfig ]] then
	ln -nsf "$DOTFILES/git/gitconfig" $HOME/.gitconfig
fi
