if which rbenv &> /dev/null; then eval "$(rbenv init -)"; fi
source "$HOME/.dotfiles/zsh/aliases"

export RBENV_ROOT="$(brew --prefix rbenv)"
export GEM_HOME="$(brew --prefix)/opt/gems"
export GEM_PATH="$(brew --prefix)/opt/gems"
