# Disable flow control so <C-s> works in vim
stty -ixon

# Path to your oh-my-zsh configuration.
export ZSH=$DOTFILES/zsh/oh-my-zsh
export ZSH_CUSTOM=$DOTFILES/zsh/customization

# Use vim keybindings
bindkey -v
bindkey -M viins 'jj' vi-cmd-mode
bindkey '^R' history-incremental-search-backward

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="jxpx777"

PROJECT_PATHS=(~/Projects ~/Projects/AG ~/Dropbox/Projects ~/go/src/github.com/agilebits)
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how many often would you like to wait before auto-updates occur? (in days)
export UPDATE_ZSH_DAYS=1
export DISABLE_UPDATE_PROMPT=true

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(brew bundler cap colorize encode64 gem git go gpg-agent jira jsontools osx pip pj pod pow rails redis-cli sublime sudo taskwarrior thor tmux urltools vagrant web-search wd)

source $ZSH/oh-my-zsh.sh
source "$DOTFILES/zsh/aliases"
# Customize to your needs...

autoload -U zmv

eval "$(rbenv init -)"

BASE16_SHELL="$DOTFILES/zsh/base16-shell/"
[ -n "$PS1" ] && [ -s $BASE16_SHELL/profile_helper.sh ] && eval "$($BASE16_SHELL/profile_helper.sh)"
base16_tomorrow


# BASE16_SCHEME="tomorrow"
# BASE16_SHELL="$DOTFILES/zsh/base16-shell/base16-$BASE16_SCHEME.light.sh"
# [[ -s $BASE16_SHELL ]] && . $BASE16_SHELL

export JIRA_URL="https://agilebits.atlassian.net"
test -e ${HOME}/.iterm2_shell_integration.zsh && source ${HOME}/.iterm2_shell_integration.zsh

export HOMEBREW_PREFIX=$(brew --prefix)
export PATH="./bin:$HOMEBREW_PREFIX/bin:$HOMEBREW_PREFIX/share/git-core/contrib/diff-highlight:$HOMEBREW_PREFIX/sbin:$HOMEBREW_PREFIX/mysql/bin:$HOMEBREW_PREFIX/share/npm/bin:$HOMEBREW_PREFIX/bin/lib/prince/bin:$PATH"

eval "$(rbenv init -)"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
[ -f /opt/boxen/env.sh ] && source /opt/boxen/env.sh
