# Path to your oh-my-zsh configuration.
ZSH=$HOME/.dotfiles/zsh/oh-my-zsh

# Use vim keybindings
bindkey -v
bindkey -M viins 'jj' vi-cmd-mode
bindkey '^R' history-incremental-search-backward

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="jxpx777"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how many often would you like to wait before auto-updates occur? (in days)
export UPDATE_ZSH_DAYS=1
export DISABLE_UPDATE_PROMPT=true

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(bundler brew cloudapp cap colorize gem git jira osx pod pow powify rails sublime terminalapp thor projects)

source $ZSH/oh-my-zsh.sh
# Customize to your needs...
export PATH=$HOME/bin:/usr/local/bin:/usr/local/sbin:/usr/local/mysql/bin:/usr/local/bin/lib/prince/bin:/Users/j/bin/Multimarkdown/bin:/Users/j/bin/abbot/bin:/Users/j/bin:/usr/local/bin:/usr/local/sbin:/usr/local/mysql:/usr/local/mysql/bin:/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/local/bin:/opt/local/sbin:/usr/local/share/npm/bin:$PATH
NODE_PATH="/usr/local/lib/node"

if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi
autoload -U zmv

source $HOME/bin/config/bash/aliases
export EDITOR='vim'
export GIT_EDITOR='vim'
export BUNDLER_EDITOR='vim'
source $HOME/.rbenv/completions/rbenv.zsh
export HOMEBREW_CASK_OPTS="--appdir=/Applications"
